### PR TITLE
Closing Issue#10-given 2 strings, find shortest string that has the 2…

### PR DESCRIPTION
**Pull request by RakshithRAcharya**
… strings as subsequences
Closing Issue #10

### CODE REVIEW

**Comment by RakshithRAcharya** [comment]
Also Digitalocean says this is an ineligible repository

**Comment by kalikidhar** [comment]
Hey @RakshithRAcharya , the code is perfectly correct , could you change the algorithm to print all possible unique shortest supersequences if there is more than one possible?
For example if the input is 
A = "ABCBDAB"
B="BDCABA"
print ABDCABDAB , ABDCBDABA , ABCBDCABA.

**Comment by kalikidhar** [comment]
> Also Digitalocean says this is an ineligible repository

Sorry about this . It should be fixed by now .

**Comment by kalikidhar** [comment]
!bounty 10

**Comment by RakshithRAcharya** [comment]
Sure.......Will try printing all the possible SuperSequences

**Pull request merged**
